

/******************************************************************************
*    NOTICE: Auto generate by tool:dbc_2_struct
*            Prohibit modification !!!!!
*            
*            
*    Tools Version  :  1.2
*    DBC file name  :  Body CAN EDU Message List V1.9 Issue.dbc
*    DBC file MD5   :  90d28e7e9c9b1de1a1c91532005834d5
*    Generate Time  :  2022/01/05 13:57:45
*            
*            
*    Author         :  Lan song yi
*            
*            
******************************************************************************/


#include "dbc2struct.h"

canFrame_t canFrames[27]=
{
    {//CAN FRAME:ABS_ESP_G         CAN ID:0x502
        .canindex   =  CanFrameIndex_ABS_ESP_G,
        .canid      =  0x502,
        .bytelen    =  7 ,
        .canbuffer  =  {0,0,0,0,0,0,0,0},
    },
    {//CAN FRAME:ADCC_4            CAN ID:0x16b
        .canindex   =  CanFrameIndex_ADCC_4,
        .canid      =  0x16b,
        .bytelen    =  8 ,
        .canbuffer  =  {0,0,0,0,0,0,0,0},
    },
    {//CAN FRAME:VCC_7             CAN ID:0x3fe
        .canindex   =  CanFrameIndex_VCC_7,
        .canid      =  0x3fe,
        .bytelen    =  8 ,
        .canbuffer  =  {0,0,0,0,0,0,0,0},
    },
    {//CAN FRAME:TMR_4             CAN ID:0x48b
        .canindex   =  CanFrameIndex_TMR_4,
        .canid      =  0x48b,
        .bytelen    =  8 ,
        .canbuffer  =  {0,0,0,0,0,0,0,0},
    },
    {//CAN FRAME:TMR_2             CAN ID:0x31e
        .canindex   =  CanFrameIndex_TMR_2,
        .canid      =  0x31e,
        .bytelen    =  8 ,
        .canbuffer  =  {0,0,0,0,0,0,0,0},
    },
    {//CAN FRAME:TMF_4             CAN ID:0x45b
        .canindex   =  CanFrameIndex_TMF_4,
        .canid      =  0x45b,
        .bytelen    =  8 ,
        .canbuffer  =  {0,0,0,0,0,0,0,0},
    },
    {//CAN FRAME:TMF_2             CAN ID:0x315
        .canindex   =  CanFrameIndex_TMF_2,
        .canid      =  0x315,
        .bytelen    =  8 ,
        .canbuffer  =  {0,0,0,0,0,0,0,0},
    },
    {//CAN FRAME:BCM_11            CAN ID:0x427
        .canindex   =  CanFrameIndex_BCM_11,
        .canid      =  0x427,
        .bytelen    =  8 ,
        .canbuffer  =  {0,0,0,0,0,0,0,0},
    },
    {//CAN FRAME:TIHU_IHU_4        CAN ID:0x519
        .canindex   =  CanFrameIndex_TIHU_IHU_4,
        .canid      =  0x519,
        .bytelen    =  8 ,
        .canbuffer  =  {0,0,0,0,0,0,0,0},
    },
    {//CAN FRAME:AC_Diagnosis6     CAN ID:0x5a2
        .canindex   =  CanFrameIndex_AC_Diagnosis6,
        .canid      =  0x5a2,
        .bytelen    =  8 ,
        .canbuffer  =  {0,0,0,0,0,0,0,0},
    },
    {//CAN FRAME:AC_Diagnosis5     CAN ID:0x5a1
        .canindex   =  CanFrameIndex_AC_Diagnosis5,
        .canid      =  0x5a1,
        .bytelen    =  8 ,
        .canbuffer  =  {0,0,0,0,0,0,0,0},
    },
    {//CAN FRAME:AC_Diagnosis4     CAN ID:0x5a5
        .canindex   =  CanFrameIndex_AC_Diagnosis4,
        .canid      =  0x5a5,
        .bytelen    =  8 ,
        .canbuffer  =  {0,0,0,0,0,0,0,0},
    },
    {//CAN FRAME:AC_Diagnosis3     CAN ID:0x5a4
        .canindex   =  CanFrameIndex_AC_Diagnosis3,
        .canid      =  0x5a4,
        .bytelen    =  8 ,
        .canbuffer  =  {0,0,0,0,0,0,0,0},
    },
    {//CAN FRAME:AC_Diagnosis2     CAN ID:0x5a7
        .canindex   =  CanFrameIndex_AC_Diagnosis2,
        .canid      =  0x5a7,
        .bytelen    =  8 ,
        .canbuffer  =  {0,0,0,0,0,0,0,0},
    },
    {//CAN FRAME:AC_Diagnosis1     CAN ID:0x5a6
        .canindex   =  CanFrameIndex_AC_Diagnosis1,
        .canid      =  0x5a6,
        .bytelen    =  8 ,
        .canbuffer  =  {0,0,0,0,0,0,0,0},
    },
    {//CAN FRAME:CLM_11            CAN ID:0x3f6
        .canindex   =  CanFrameIndex_CLM_11,
        .canid      =  0x3f6,
        .bytelen    =  8 ,
        .canbuffer  =  {0,0,0,0,0,0,0,0},
    },
    {//CAN FRAME:CLM_2             CAN ID:0x535
        .canindex   =  CanFrameIndex_CLM_2,
        .canid      =  0x535,
        .bytelen    =  8 ,
        .canbuffer  =  {0,0,0,0,0,0,0,0},
    },
    {//CAN FRAME:CLM_1             CAN ID:0x51a
        .canindex   =  CanFrameIndex_CLM_1,
        .canid      =  0x51a,
        .bytelen    =  8 ,
        .canbuffer  =  {0,0,0,0,0,0,0,0},
    },
    {//CAN FRAME:OBC_4             CAN ID:0x43c
        .canindex   =  CanFrameIndex_OBC_4,
        .canid      =  0x43c,
        .bytelen    =  8 ,
        .canbuffer  =  {0,0,0,0,0,0,0,0},
    },
    {//CAN FRAME:OBC_3             CAN ID:0x42b
        .canindex   =  CanFrameIndex_OBC_3,
        .canid      =  0x42b,
        .bytelen    =  8 ,
        .canbuffer  =  {0,0,0,0,0,0,0,0},
    },
    {//CAN FRAME:DCDC_1            CAN ID:0x418
        .canindex   =  CanFrameIndex_DCDC_1,
        .canid      =  0x418,
        .bytelen    =  8 ,
        .canbuffer  =  {0,0,0,0,0,0,0,0},
    },
    {//CAN FRAME:BMS_7             CAN ID:0x426
        .canindex   =  CanFrameIndex_BMS_7,
        .canid      =  0x426,
        .bytelen    =  8 ,
        .canbuffer  =  {0,0,0,0,0,0,0,0},
    },
    {//CAN FRAME:BMS_5             CAN ID:0x41b
        .canindex   =  CanFrameIndex_BMS_5,
        .canid      =  0x41b,
        .bytelen    =  8 ,
        .canbuffer  =  {0,0,0,0,0,0,0,0},
    },
    {//CAN FRAME:BMS_4             CAN ID:0x41f
        .canindex   =  CanFrameIndex_BMS_4,
        .canid      =  0x41f,
        .bytelen    =  8 ,
        .canbuffer  =  {0,0,0,0,0,0,0,0},
    },
    {//CAN FRAME:BMS_2             CAN ID:0x208
        .canindex   =  CanFrameIndex_BMS_2,
        .canid      =  0x208,
        .bytelen    =  8 ,
        .canbuffer  =  {0,0,0,0,0,0,0,0},
    },
    {//CAN FRAME:AIPM_2            CAN ID:0x4f3
        .canindex   =  CanFrameIndex_AIPM_2,
        .canid      =  0x4f3,
        .bytelen    =  8 ,
        .canbuffer  =  {0,0,0,0,0,0,0,0},
    },
    {//CAN FRAME:AIPM_1            CAN ID:0x4f1
        .canindex   =  CanFrameIndex_AIPM_1,
        .canid      =  0x4f1,
        .bytelen    =  8 ,
        .canbuffer  =  {0,0,0,0,0,0,0,0},
    },
};
signalFrame_t singalFrames[140]=
{
    //CAN FRAME:ABS_ESP_G         CAN ID:0x502
    {
        .signalIndex    =  CanSingalIndex_VehicleSpeedVSOSigValidData,
        .canFrameIndex  =  CanFrameIndex_ABS_ESP_G,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  31,
        .bitlen         =  1,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_VehicleSpeedVSOSig,
        .canFrameIndex  =  CanFrameIndex_ABS_ESP_G,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  12,
        .bitlen         =  13,
        .factor         =  0.0625,
        .offset         =  0,
    },
    //CAN FRAME:ADCC_4            CAN ID:0x16b
    {
        .signalIndex    =  CanSingalIndex_ADCC_4_CRC,
        .canFrameIndex  =  CanFrameIndex_ADCC_4,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  63,
        .bitlen         =  8,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_ADCC_4_Message_Counter,
        .canFrameIndex  =  CanFrameIndex_ADCC_4,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  51,
        .bitlen         =  4,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_ADCC_DelayReq,
        .canFrameIndex  =  CanFrameIndex_ADCC_4,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  6,
        .bitlen         =  1,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_ADCC_CoolantFlowReq,
        .canFrameIndex  =  CanFrameIndex_ADCC_4,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  5,
        .bitlen         =  6,
        .factor         =  0.25,
        .offset         =  0,
    },
    //CAN FRAME:VCC_7             CAN ID:0x3fe
    {
        .signalIndex    =  CanSingalIndex_VCC_EACAllow,
        .canFrameIndex  =  CanFrameIndex_VCC_7,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  18,
        .bitlen         =  1,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_VCC_HVHAllow,
        .canFrameIndex  =  CanFrameIndex_VCC_7,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  19,
        .bitlen         =  1,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_VCC_HVReady,
        .canFrameIndex  =  CanFrameIndex_VCC_7,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  20,
        .bitlen         =  1,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_VCC_MotorHeatPwrAct,
        .canFrameIndex  =  CanFrameIndex_VCC_7,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  13,
        .bitlen         =  9,
        .factor         =  0.1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_VCC_EDUSystemPowerLimit,
        .canFrameIndex  =  CanFrameIndex_VCC_7,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  7,
        .bitlen         =  10,
        .factor         =  0.04,
        .offset         =  0,
    },
    //CAN FRAME:TMR_4             CAN ID:0x48b
    {
        .signalIndex    =  CanSingalIndex_TMR_StatorTemperature,
        .canFrameIndex  =  CanFrameIndex_TMR_4,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  22,
        .bitlen         =  9,
        .factor         =  1,
        .offset         =  -40,
    },
    {
        .signalIndex    =  CanSingalIndex_TMR_InverterTemperature,
        .canFrameIndex  =  CanFrameIndex_TMR_4,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  7,
        .bitlen         =  8,
        .factor         =  1,
        .offset         =  -40,
    },
    //CAN FRAME:TMR_2             CAN ID:0x31e
    {
        .signalIndex    =  CanSingalIndex_TMR_CoolantFlow,
        .canFrameIndex  =  CanFrameIndex_TMR_2,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  29,
        .bitlen         =  6,
        .factor         =  0.25,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_TMR_CoolantTemp,
        .canFrameIndex  =  CanFrameIndex_TMR_2,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  7,
        .bitlen         =  8,
        .factor         =  1,
        .offset         =  -40,
    },
    //CAN FRAME:TMF_4             CAN ID:0x45b
    {
        .signalIndex    =  CanSingalIndex_TMF_StatTemp,
        .canFrameIndex  =  CanFrameIndex_TMF_4,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  24,
        .bitlen         =  9,
        .factor         =  1,
        .offset         =  -40,
    },
    {
        .signalIndex    =  CanSingalIndex_TMF_InvTemp,
        .canFrameIndex  =  CanFrameIndex_TMF_4,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  7,
        .bitlen         =  8,
        .factor         =  1,
        .offset         =  -40,
    },
    //CAN FRAME:TMF_2             CAN ID:0x315
    {
        .signalIndex    =  CanSingalIndex_TMF_CoolantFlowReq,
        .canFrameIndex  =  CanFrameIndex_TMF_2,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  29,
        .bitlen         =  6,
        .factor         =  0.25,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_TMF_CoolantTemp,
        .canFrameIndex  =  CanFrameIndex_TMF_2,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  7,
        .bitlen         =  8,
        .factor         =  1,
        .offset         =  -40,
    },
    //CAN FRAME:BCM_11            CAN ID:0x427
    {
        .signalIndex    =  CanSingalIndex_RLS_TempDewPoint,
        .canFrameIndex  =  CanFrameIndex_BCM_11,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  42,
        .bitlen         =  11,
        .factor         =  0.1,
        .offset         =  -39.6,
    },
    {
        .signalIndex    =  CanSingalIndex_RLS_Humid_Temp_Error,
        .canFrameIndex  =  CanFrameIndex_BCM_11,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  43,
        .bitlen         =  1,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_RLS_HumidSensorValue,
        .canFrameIndex  =  CanFrameIndex_BCM_11,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  39,
        .bitlen         =  8,
        .factor         =  0.5,
        .offset         =  -0.5,
    },
    {
        .signalIndex    =  CanSingalIndex_RLS_TempSensorValue,
        .canFrameIndex  =  CanFrameIndex_BCM_11,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  23,
        .bitlen         =  8,
        .factor         =  0.5,
        .offset         =  -40,
    },
    //CAN FRAME:TIHU_IHU_4        CAN ID:0x519
    {
        .signalIndex    =  CanSingalIndex_HU_ZoneSelectionKeySts,
        .canFrameIndex  =  CanFrameIndex_TIHU_IHU_4,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  53,
        .bitlen         =  2,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_HU_SetCirculationModeKeySts,
        .canFrameIndex  =  CanFrameIndex_TIHU_IHU_4,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  51,
        .bitlen         =  2,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_HU_SetTemperature_R_C,
        .canFrameIndex  =  CanFrameIndex_TIHU_IHU_4,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  22,
        .bitlen         =  5,
        .factor         =  1,
        .offset         =  17,
    },
    {
        .signalIndex    =  CanSingalIndex_HU_SetTemperature_L_C,
        .canFrameIndex  =  CanFrameIndex_TIHU_IHU_4,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  11,
        .bitlen         =  5,
        .factor         =  1,
        .offset         =  17,
    },
    {
        .signalIndex    =  CanSingalIndex_HU_ModeAdjustKeySts,
        .canFrameIndex  =  CanFrameIndex_TIHU_IHU_4,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  15,
        .bitlen         =  3,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_HU_SetMaxFrontDeforestSts,
        .canFrameIndex  =  CanFrameIndex_TIHU_IHU_4,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  7,
        .bitlen         =  2,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_HU_BlowSpeedLevelKeySts,
        .canFrameIndex  =  CanFrameIndex_TIHU_IHU_4,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  5,
        .bitlen         =  3,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_HU_SetAutoKeySts,
        .canFrameIndex  =  CanFrameIndex_TIHU_IHU_4,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  63,
        .bitlen         =  2,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_HU_SetACRequestKeySts,
        .canFrameIndex  =  CanFrameIndex_TIHU_IHU_4,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  43,
        .bitlen         =  2,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_HU_SetCLMOn,
        .canFrameIndex  =  CanFrameIndex_TIHU_IHU_4,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  41,
        .bitlen         =  2,
        .factor         =  1,
        .offset         =  0,
    },
    //CAN FRAME:AC_Diagnosis6     CAN ID:0x5a2
    //CAN FRAME:AC_Diagnosis5     CAN ID:0x5a1
    //CAN FRAME:AC_Diagnosis4     CAN ID:0x5a5
    {
        .signalIndex    =  CanSingalIndex_Test8_T,
        .canFrameIndex  =  CanFrameIndex_AC_Diagnosis4,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  63,
        .bitlen         =  8,
        .factor         =  1,
        .offset         =  -40,
    },
    {
        .signalIndex    =  CanSingalIndex_Test7_T,
        .canFrameIndex  =  CanFrameIndex_AC_Diagnosis4,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  55,
        .bitlen         =  8,
        .factor         =  1,
        .offset         =  -40,
    },
    {
        .signalIndex    =  CanSingalIndex_Test6_T,
        .canFrameIndex  =  CanFrameIndex_AC_Diagnosis4,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  47,
        .bitlen         =  8,
        .factor         =  1,
        .offset         =  -40,
    },
    {
        .signalIndex    =  CanSingalIndex_Test5_T,
        .canFrameIndex  =  CanFrameIndex_AC_Diagnosis4,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  39,
        .bitlen         =  8,
        .factor         =  1,
        .offset         =  -40,
    },
    {
        .signalIndex    =  CanSingalIndex_Test4_T,
        .canFrameIndex  =  CanFrameIndex_AC_Diagnosis4,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  31,
        .bitlen         =  8,
        .factor         =  1,
        .offset         =  -40,
    },
    {
        .signalIndex    =  CanSingalIndex_Test3_T,
        .canFrameIndex  =  CanFrameIndex_AC_Diagnosis4,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  23,
        .bitlen         =  8,
        .factor         =  1,
        .offset         =  -40,
    },
    {
        .signalIndex    =  CanSingalIndex_Test2_T,
        .canFrameIndex  =  CanFrameIndex_AC_Diagnosis4,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  15,
        .bitlen         =  8,
        .factor         =  1,
        .offset         =  -40,
    },
    {
        .signalIndex    =  CanSingalIndex_Test1_P,
        .canFrameIndex  =  CanFrameIndex_AC_Diagnosis4,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  7,
        .bitlen         =  8,
        .factor         =  0.02,
        .offset         =  0,
    },
    //CAN FRAME:AC_Diagnosis3     CAN ID:0x5a4
    {
        .signalIndex    =  CanSingalIndex_PT_Sensor2_T,
        .canFrameIndex  =  CanFrameIndex_AC_Diagnosis3,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  63,
        .bitlen         =  8,
        .factor         =  1,
        .offset         =  -40,
    },
    {
        .signalIndex    =  CanSingalIndex_PT_Sensor2_P,
        .canFrameIndex  =  CanFrameIndex_AC_Diagnosis3,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  55,
        .bitlen         =  8,
        .factor         =  0.01,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_PT_Sensor1_T,
        .canFrameIndex  =  CanFrameIndex_AC_Diagnosis3,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  47,
        .bitlen         =  8,
        .factor         =  1,
        .offset         =  -40,
    },
    {
        .signalIndex    =  CanSingalIndex_PT_Sensor1_P,
        .canFrameIndex  =  CanFrameIndex_AC_Diagnosis3,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  39,
        .bitlen         =  8,
        .factor         =  0.01,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_AC_ModeDC_Actual,
        .canFrameIndex  =  CanFrameIndex_AC_Diagnosis3,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  31,
        .bitlen         =  8,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_AC_ModeDC_Req,
        .canFrameIndex  =  CanFrameIndex_AC_Diagnosis3,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  23,
        .bitlen         =  8,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_AC_RecDC_Actual,
        .canFrameIndex  =  CanFrameIndex_AC_Diagnosis3,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  15,
        .bitlen         =  8,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_AC_RecDC_Req,
        .canFrameIndex  =  CanFrameIndex_AC_Diagnosis3,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  7,
        .bitlen         =  8,
        .factor         =  1,
        .offset         =  0,
    },
    //CAN FRAME:AC_Diagnosis2     CAN ID:0x5a7
    {
        .signalIndex    =  CanSingalIndex_AC_MixDC_Right_Actual,
        .canFrameIndex  =  CanFrameIndex_AC_Diagnosis2,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  63,
        .bitlen         =  8,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_AC_MixDC_Right_Req,
        .canFrameIndex  =  CanFrameIndex_AC_Diagnosis2,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  55,
        .bitlen         =  8,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_AC_MixDC_Left_Actual,
        .canFrameIndex  =  CanFrameIndex_AC_Diagnosis2,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  47,
        .bitlen         =  8,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_AC_MixDC_Left_Req,
        .canFrameIndex  =  CanFrameIndex_AC_Diagnosis2,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  39,
        .bitlen         =  8,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_AC_u16PUMP3_PWM_Req,
        .canFrameIndex  =  CanFrameIndex_AC_Diagnosis2,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  31,
        .bitlen         =  8,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_AC_u16PUMP2_PWM_Req,
        .canFrameIndex  =  CanFrameIndex_AC_Diagnosis2,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  23,
        .bitlen         =  8,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_AC_u16PUMP1_PWM_Req,
        .canFrameIndex  =  CanFrameIndex_AC_Diagnosis2,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  15,
        .bitlen         =  8,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_AC_u16FRFAN_PWM_Req,
        .canFrameIndex  =  CanFrameIndex_AC_Diagnosis2,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  7,
        .bitlen         =  8,
        .factor         =  1,
        .offset         =  0,
    },
    //CAN FRAME:AC_Diagnosis1     CAN ID:0x5a6
    {
        .signalIndex    =  CanSingalIndex_EXV2_Postion,
        .canFrameIndex  =  CanFrameIndex_AC_Diagnosis1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  55,
        .bitlen         =  16,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_EXV1_Postion,
        .canFrameIndex  =  CanFrameIndex_AC_Diagnosis1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  39,
        .bitlen         =  16,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_AC_EDC_Power,
        .canFrameIndex  =  CanFrameIndex_AC_Diagnosis1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  31,
        .bitlen         =  8,
        .factor         =  40,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_AC_EDC_PowerReq,
        .canFrameIndex  =  CanFrameIndex_AC_Diagnosis1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  23,
        .bitlen         =  8,
        .factor         =  40,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_AC_EDC_Speed,
        .canFrameIndex  =  CanFrameIndex_AC_Diagnosis1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  15,
        .bitlen         =  8,
        .factor         =  50,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_AC_EDC_SpeedReq,
        .canFrameIndex  =  CanFrameIndex_AC_Diagnosis1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  7,
        .bitlen         =  8,
        .factor         =  50,
        .offset         =  0,
    },
    //CAN FRAME:CLM_11            CAN ID:0x3f6
    {
        .signalIndex    =  CanSingalIndex_TMR_InletWaterTemp,
        .canFrameIndex  =  CanFrameIndex_CLM_11,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  63,
        .bitlen         =  8,
        .factor         =  1,
        .offset         =  -40,
    },
    {
        .signalIndex    =  CanSingalIndex_CLM_TMRHeatReq,
        .canFrameIndex  =  CanFrameIndex_CLM_11,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  49,
        .bitlen         =  1,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_HVH_Sts,
        .canFrameIndex  =  CanFrameIndex_CLM_11,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  52,
        .bitlen         =  3,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_EAC_Sts,
        .canFrameIndex  =  CanFrameIndex_CLM_11,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  55,
        .bitlen         =  3,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_CLM_TMFCoolantFlow,
        .canFrameIndex  =  CanFrameIndex_CLM_11,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  45,
        .bitlen         =  6,
        .factor         =  0.25,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_HVH_HV_voltage,
        .canFrameIndex  =  CanFrameIndex_CLM_11,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  39,
        .bitlen         =  10,
        .factor         =  2,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_CLM_TMRCoolantFlow,
        .canFrameIndex  =  CanFrameIndex_CLM_11,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  29,
        .bitlen         =  6,
        .factor         =  0.25,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_EAC_uHvAcnCpr,
        .canFrameIndex  =  CanFrameIndex_CLM_11,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  23,
        .bitlen         =  10,
        .factor         =  2,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_HVH_DC_curr,
        .canFrameIndex  =  CanFrameIndex_CLM_11,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  15,
        .bitlen         =  8,
        .factor         =  0.25,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_EAC_iHvAcnCpr,
        .canFrameIndex  =  CanFrameIndex_CLM_11,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  7,
        .bitlen         =  8,
        .factor         =  0.5,
        .offset         =  0,
    },
    //CAN FRAME:CLM_2             CAN ID:0x535
    {
        .signalIndex    =  CanSingalIndex_CLM2_ExternalTemperature_C,
        .canFrameIndex  =  CanFrameIndex_CLM_2,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  31,
        .bitlen         =  8,
        .factor         =  0.5,
        .offset         =  -55,
    },
    {
        .signalIndex    =  CanSingalIndex_CLM2_ExternalTempFailSts,
        .canFrameIndex  =  CanFrameIndex_CLM_2,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  16,
        .bitlen         =  1,
        .factor         =  1,
        .offset         =  0,
    },
    //CAN FRAME:CLM_1             CAN ID:0x51a
    {
        .signalIndex    =  CanSingalIndex_Reserved_ANION_request,
        .canFrameIndex  =  CanFrameIndex_CLM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  56,
        .bitlen         =  1,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_SetTemperature_R_F,
        .canFrameIndex  =  CanFrameIndex_CLM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  61,
        .bitlen         =  5,
        .factor         =  2,
        .offset         =  58,
    },
    {
        .signalIndex    =  CanSingalIndex_SetTemperature_L_F,
        .canFrameIndex  =  CanFrameIndex_CLM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  50,
        .bitlen         =  5,
        .factor         =  2,
        .offset         =  58,
    },
    {
        .signalIndex    =  CanSingalIndex_SelfTestResult,
        .canFrameIndex  =  CanFrameIndex_CLM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  55,
        .bitlen         =  5,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_TemperatureUnit,
        .canFrameIndex  =  CanFrameIndex_CLM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  40,
        .bitlen         =  1,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_ZoneSelectionDisplaySts,
        .canFrameIndex  =  CanFrameIndex_CLM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  41,
        .bitlen         =  1,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_CirculationModeDisplaySts,
        .canFrameIndex  =  CanFrameIndex_CLM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  42,
        .bitlen         =  1,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_SetTemperature_R_C,
        .canFrameIndex  =  CanFrameIndex_CLM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  47,
        .bitlen         =  5,
        .factor         =  1,
        .offset         =  17,
    },
    {
        .signalIndex    =  CanSingalIndex_SetTemperature_L_C,
        .canFrameIndex  =  CanFrameIndex_CLM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  39,
        .bitlen         =  5,
        .factor         =  1,
        .offset         =  17,
    },
    {
        .signalIndex    =  CanSingalIndex_BlowDelayOffSts,
        .canFrameIndex  =  CanFrameIndex_CLM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  34,
        .bitlen         =  1,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_BlowAdvanceOnSts,
        .canFrameIndex  =  CanFrameIndex_CLM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  33,
        .bitlen         =  1,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_DisplayActive,
        .canFrameIndex  =  CanFrameIndex_CLM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  32,
        .bitlen         =  1,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_SelfTestActive,
        .canFrameIndex  =  CanFrameIndex_CLM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  27,
        .bitlen         =  1,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_PM2_5Sts,
        .canFrameIndex  =  CanFrameIndex_CLM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  26,
        .bitlen         =  1,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_WorkingSts,
        .canFrameIndex  =  CanFrameIndex_CLM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  25,
        .bitlen         =  1,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_ISSInhibitACSts,
        .canFrameIndex  =  CanFrameIndex_CLM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  24,
        .bitlen         =  1,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_ModeAdjustDisplaySts,
        .canFrameIndex  =  CanFrameIndex_CLM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  30,
        .bitlen         =  3,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_FrontDeforest_MaxDisplaySts,
        .canFrameIndex  =  CanFrameIndex_CLM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  31,
        .bitlen         =  1,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_ACRequestDisplaySts,
        .canFrameIndex  =  CanFrameIndex_CLM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  19,
        .bitlen         =  1,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_BlowSpeedLevelDisplaySts,
        .canFrameIndex  =  CanFrameIndex_CLM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  18,
        .bitlen         =  3,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_AutoDisplaySts,
        .canFrameIndex  =  CanFrameIndex_CLM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  20,
        .bitlen         =  1,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_ACRequestCommand,
        .canFrameIndex  =  CanFrameIndex_CLM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  21,
        .bitlen         =  1,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_Reserved_AC_MaxSts,
        .canFrameIndex  =  CanFrameIndex_CLM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  22,
        .bitlen         =  1,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_ExternalTemperatureFailSts,
        .canFrameIndex  =  CanFrameIndex_CLM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  23,
        .bitlen         =  1,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_ExternalTemperature_C,
        .canFrameIndex  =  CanFrameIndex_CLM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  15,
        .bitlen         =  8,
        .factor         =  0.5,
        .offset         =  -55,
    },
    {
        .signalIndex    =  CanSingalIndex_ExternalTemperature_F,
        .canFrameIndex  =  CanFrameIndex_CLM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  7,
        .bitlen         =  8,
        .factor         =  1,
        .offset         =  -67,
    },
    //CAN FRAME:OBC_4             CAN ID:0x43c
    {
        .signalIndex    =  CanSingalIndex_OBC_CoolingReq,
        .canFrameIndex  =  CanFrameIndex_OBC_4,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  54,
        .bitlen         =  1,
        .factor         =  1,
        .offset         =  0,
    },
    //CAN FRAME:OBC_3             CAN ID:0x42b
    {
        .signalIndex    =  CanSingalIndex_OBC_ChargerTemp,
        .canFrameIndex  =  CanFrameIndex_OBC_3,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  15,
        .bitlen         =  8,
        .factor         =  1,
        .offset         =  -40,
    },
    //CAN FRAME:DCDC_1            CAN ID:0x418
    {
        .signalIndex    =  CanSingalIndex_DCDC_OverTemp,
        .canFrameIndex  =  CanFrameIndex_DCDC_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  42,
        .bitlen         =  1,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_DCDC_CoolingReq,
        .canFrameIndex  =  CanFrameIndex_DCDC_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  34,
        .bitlen         =  1,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_DCDC_Temp,
        .canFrameIndex  =  CanFrameIndex_DCDC_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  23,
        .bitlen         =  8,
        .factor         =  1,
        .offset         =  -40,
    },
    //CAN FRAME:BMS_7             CAN ID:0x426
    {
        .signalIndex    =  CanSingalIndex_BMS_AverageBattTemp,
        .canFrameIndex  =  CanFrameIndex_BMS_7,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  23,
        .bitlen         =  8,
        .factor         =  1,
        .offset         =  -40,
    },
    {
        .signalIndex    =  CanSingalIndex_BMS_LowestBattTemp,
        .canFrameIndex  =  CanFrameIndex_BMS_7,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  15,
        .bitlen         =  8,
        .factor         =  1,
        .offset         =  -40,
    },
    {
        .signalIndex    =  CanSingalIndex_BMS_HighestBattTemp,
        .canFrameIndex  =  CanFrameIndex_BMS_7,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  7,
        .bitlen         =  8,
        .factor         =  1,
        .offset         =  -40,
    },
    //CAN FRAME:BMS_5             CAN ID:0x41b
    {
        .signalIndex    =  CanSingalIndex_BMS_HeatRequest_Mode,
        .canFrameIndex  =  CanFrameIndex_BMS_5,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  42,
        .bitlen         =  3,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_BMS_Request_Mode,
        .canFrameIndex  =  CanFrameIndex_BMS_5,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  3,
        .bitlen         =  4,
        .factor         =  1,
        .offset         =  0,
    },
    //CAN FRAME:BMS_4             CAN ID:0x41f
    {
        .signalIndex    =  CanSingalIndex_BMS_Request_FlowRate,
        .canFrameIndex  =  CanFrameIndex_BMS_4,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  31,
        .bitlen         =  8,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_BMS_WaterTemp_InletTarget,
        .canFrameIndex  =  CanFrameIndex_BMS_4,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  23,
        .bitlen         =  8,
        .factor         =  1,
        .offset         =  -40,
    },
    {
        .signalIndex    =  CanSingalIndex_BMS_WaterTemp_Outlet,
        .canFrameIndex  =  CanFrameIndex_BMS_4,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  15,
        .bitlen         =  8,
        .factor         =  1,
        .offset         =  -40,
    },
    {
        .signalIndex    =  CanSingalIndex_BMS_WaterTemp_Inlet,
        .canFrameIndex  =  CanFrameIndex_BMS_4,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  7,
        .bitlen         =  8,
        .factor         =  1,
        .offset         =  -40,
    },
    //CAN FRAME:BMS_2             CAN ID:0x208
    {
        .signalIndex    =  CanSingalIndex_BMS_Chg_Sts,
        .canFrameIndex  =  CanFrameIndex_BMS_2,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  39,
        .bitlen         =  4,
        .factor         =  1,
        .offset         =  0,
    },
    //CAN FRAME:AIPM_2            CAN ID:0x4f3
    {
        .signalIndex    =  CanSingalIndex_PM_2_5KeyPresent,
        .canFrameIndex  =  CanFrameIndex_AIPM_2,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  25,
        .bitlen         =  2,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_SurfaceTempRaw_C,
        .canFrameIndex  =  CanFrameIndex_AIPM_2,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  19,
        .bitlen         =  10,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_OnBoardTempRaw_C,
        .canFrameIndex  =  CanFrameIndex_AIPM_2,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  13,
        .bitlen         =  10,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_SolarSenRaw,
        .canFrameIndex  =  CanFrameIndex_AIPM_2,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  7,
        .bitlen         =  10,
        .factor         =  1,
        .offset         =  0,
    },
    //CAN FRAME:AIPM_1            CAN ID:0x4f1
    {
        .signalIndex    =  CanSingalIndex_Key19Sts,
        .canFrameIndex  =  CanFrameIndex_AIPM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  60,
        .bitlen         =  1,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_Key18Sts,
        .canFrameIndex  =  CanFrameIndex_AIPM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  59,
        .bitlen         =  1,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_Key17Sts,
        .canFrameIndex  =  CanFrameIndex_AIPM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  58,
        .bitlen         =  1,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_BlowerSilderSts,
        .canFrameIndex  =  CanFrameIndex_AIPM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  63,
        .bitlen         =  3,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_BlowLevelPlusMinusSts,
        .canFrameIndex  =  CanFrameIndex_AIPM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  50,
        .bitlen         =  2,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_Key14Sts,
        .canFrameIndex  =  CanFrameIndex_AIPM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  46,
        .bitlen         =  1,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_BlowerSlidPlusMinusSts,
        .canFrameIndex  =  CanFrameIndex_AIPM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  45,
        .bitlen         =  2,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_Key16Sts,
        .canFrameIndex  =  CanFrameIndex_AIPM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  43,
        .bitlen         =  1,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_Key13Sts,
        .canFrameIndex  =  CanFrameIndex_AIPM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  42,
        .bitlen         =  1,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_Key10Sts,
        .canFrameIndex  =  CanFrameIndex_AIPM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  39,
        .bitlen         =  1,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_TemperatureUnitKeySts,
        .canFrameIndex  =  CanFrameIndex_AIPM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  38,
        .bitlen         =  1,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_SelfTestActiveKeySts,
        .canFrameIndex  =  CanFrameIndex_AIPM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  37,
        .bitlen         =  1,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_Key9Sts,
        .canFrameIndex  =  CanFrameIndex_AIPM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  31,
        .bitlen         =  1,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_Key8Sts,
        .canFrameIndex  =  CanFrameIndex_AIPM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  30,
        .bitlen         =  1,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_Key7Sts,
        .canFrameIndex  =  CanFrameIndex_AIPM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  29,
        .bitlen         =  1,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_Knob3Sts,
        .canFrameIndex  =  CanFrameIndex_AIPM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  36,
        .bitlen         =  5,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_Knob2Sts,
        .canFrameIndex  =  CanFrameIndex_AIPM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  28,
        .bitlen         =  5,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_Key15Sts,
        .canFrameIndex  =  CanFrameIndex_AIPM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  22,
        .bitlen         =  1,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_RightTempPlusMinusSts,
        .canFrameIndex  =  CanFrameIndex_AIPM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  21,
        .bitlen         =  2,
        .factor         =  1,
        .offset         =  0,
    },
    {
        .signalIndex    =  CanSingalIndex_LeftTempPlusMinusSts,
        .canFrameIndex  =  CanFrameIndex_AIPM_1,
        .byteorder      =  BYTEORDE_MOTOROLA,
        .bitstart       =  19,
        .bitlen         =  2,
        .factor         =  1,
        .offset         =  0,
    },
};
