/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : spi1.c
**     Project     : S32DS_PE_MCAL_Pr
**     Processor   : S32K144_64
**     Component   : spi_pal
**     Version     : Component SDK_S32K1xx_15, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_S32K1xx_15
**     Compiler    : GNU C Compiler
**     Date/Time   : 2021-11-12, 09:56, # CodeGen: 0
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc. 
**     Copyright 2016-2017 NXP 
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file spi1.c
** @version 01.00
*/         
/*!
**  @addtogroup spi1_module spi1 module documentation
**  @{
*/         
#include "spi1.h"

/*
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External could be made static.
 * This structure is defined for usage by application code.
 *
 */

/*! @brief SPI_PAL instance */
spi_instance_t spi1Instance =
{
    .instType = SPI_INST_TYPE_LPSPI,
    .instIdx = 2U
};

/* SPI Master Configurations */
const spi_master_t spi1_MasterConfig0 =
{
    .baudRate      = 1000000,
    .ssPolarity    = SPI_ACTIVE_LOW,
    .frameSize     = 16,
    .clockPhase    = READ_ON_EVEN_EDGE,
    .clockPolarity = SPI_ACTIVE_HIGH,
    .bitOrder      = SPI_TRANSFER_LSB_FIRST,
    .transferType  = SPI_USING_INTERRUPTS,
    .rxDMAChannel  = 255U,
    .txDMAChannel  = 255U,
    .callback      = NULL,
    .callbackParam = NULL,
    .ssPin         = 0,
    .extension     = NULL 
};
 
/* SPI Slave Configurations */
const spi_slave_t spi1_SlaveConfig0 =
{
    .ssPolarity     = SPI_ACTIVE_LOW,
    .frameSize      = 8,
    .clockPhase     = READ_ON_ODD_EDGE,
    .clockPolarity  = SPI_ACTIVE_HIGH,
    .transferType   = SPI_USING_INTERRUPTS,
    .rxDMAChannel   = 255U,
    .txDMAChannel   = 255U,
    .callback       = NULL,
    .callbackParam  = NULL
};
/* END spi1. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the Freescale S32K series of microcontrollers.
**
** ###################################################################
*/

